### ISSUE TITLE
External Storage Support

### ISSUE THREAD

**Issue by autodistries** [deltazefiro/Amarok-Hider#9]
Hi, it would be useful for the FileHider to work for external storage folders.
For now, folders in external storage seem to be ignored.
Thanks.

**Comment by deltazefiro** [comment]
Hmm I do not have a device with external storage — so what problem did you meet when you tried to hide external storage?

**Comment by deltazefiro** [comment]
> > Hmm I do not have a device with external storage — so what problem did you meet when you tried to hide folders in external storage?
> 
> he said they were ignored

@Wjxfi  I mean, does the FileHider indicate any errors (i.e. alert dialog, Toast)?   
Or it just skips files in external storage silently?

**Comment by deltazefiro** [comment]
> I checked, there are no errors. it just ignores it

Strange. Could you check if the path shown in the `Set Hide Files` menu matches the correct folder path?  
For internal storage, the path should start with `/storage/emulated/0/`, but for external one that should be different.  

btw, are you convenient enough to catch logs with logcat?
Could you provide the log of:

1. Adding a new external storage folder in `Set Hide Files`
2. Perform the hiding

That helps a lot.

**Comment by deltazefiro** [comment]
> > For internal storage, the path should start with `/storage/emulated/0/`, but for external one that should be different.
> 
> really, that's the problem ![294370.jpg](https://user-images.githubusercontent.com/113500363/210066623-fd9f6a02-5ae5-4d7e-87d5-705fd3251949.jpg)

Thanks. I've reproduced this issue.  
WIP.

**Comment by deltazefiro** [comment]
Fixed! Try the latest [pre-release](https://github.com/deltazefiro/Amarok-Hider/releases/tag/v0.8.1b2)!  
If it does not work, please tell me.  
Happy New Year!

**Comment by autodistries** [comment]
Heya ! I tried with the pre-release, and the problem remains. I got you a logcat ! The problem seems to be that the app always thinks the folder is in internal storage, and checks under /storage/emulated/0/folder instead of in /storage/XXXX-XXXX/folder. See:



```
[01-02 14:39:59.928 9118:9153 I/Hider]
Unhiding files ...

[01-02 14:39:59.929 9118:9153 I/FileHider]
Applying hider to: /storage/emulated/0/Download/E

[01-02 14:39:59.935 9118:9153 W/FileHider]
While processing 'E': java.nio.file.NoSuchFileException: /storage/emulated/0/Download/E

[01-02 14:39:59.935 9118:9153 I/Hider]
No hide App, skipped App unhiding.

[01-02 14:39:59.935 9118:9153 I/Hider]
Dusk to Dusk! Night has come!

--------------------------

[01-02 14:40:03.743 9118:9153 I/Hider]
Hiding files ...

[01-02 14:40:03.743 9118:9153 I/FileHider]
Applying hider to: /storage/emulated/0/Download/E

[01-02 14:40:03.752 9118:9153 W/FileHider]
While processing 'E': java.nio.file.NoSuchFileException: /storage/emulated/0/Download/E

[01-02 14:40:03.752 9118:9153 I/Hider]
No hide App, skipped App hiding.

[01-02 14:40:03.752 9118:9153 I/Hider]
Hid. Dusk to Dawn! Goodmorning ~
```

**Comment by deltazefiro** [comment]
> Heya ! I tried with the pre-release, and the problem remains. I got you a logcat ! The problem seems to be that the app always thinks the folder is in internal storage, and checks under /storage/emulated/0/folder instead of in /storage/XXXX-XXXX/folder. So it only remembers /path/to/folder instead of /storage/..../path/to/folder. See:
> 
> ```
> [01-02 14:39:59.928 9118:9153 I/Hider]
> Unhiding files ...
> 
> [01-02 14:39:59.929 9118:9153 I/FileHider]
> Applying hider to: /storage/emulated/0/Download/E
> 
> [01-02 14:39:59.935 9118:9153 W/FileHider]
> While processing 'E': java.nio.file.NoSuchFileException: /storage/emulated/0/Download/E
> 
> [01-02 14:39:59.935 9118:9153 I/Hider]
> No hide App, skipped App unhiding.
> 
> [01-02 14:39:59.935 9118:9153 I/Hider]
> Dusk to Dusk! Night has come!
> 
> --------------------------
> 
> [01-02 14:40:03.743 9118:9153 I/Hider]
> Hiding files ...
> 
> [01-02 14:40:03.743 9118:9153 I/FileHider]
> Applying hider to: /storage/emulated/0/Download/E
> 
> [01-02 14:40:03.752 9118:9153 W/FileHider]
> While processing 'E': java.nio.file.NoSuchFileException: /storage/emulated/0/Download/E
> 
> [01-02 14:40:03.752 9118:9153 I/Hider]
> No hide App, skipped App hiding.
> 
> [01-02 14:40:03.752 9118:9153 I/Hider]
> Hid. Dusk to Dawn! Goodmorning ~
> ```

Hi @autodistries !  
Have you tried removing that path from the `Set Hide File` menu and adding it again after you update?  
If you have done so, would you like to catch the log when adding that path to `Set Hide File`?  
And, perhaps you can provide the following information:  

**Basic Information (please complete the following information) / 请填写以下信息:**
 - OS (ROM) / 系统: [e.g. MIUI 13]
 - Android Version / 安卓版本: [e.g. 12]
 - Amarok Version / Amarok版本: [e.g. v0.8.1b1-foss]

**Comment by autodistries** [comment]
Hey, I just tried adding folder12onSD which is on my SD card after performing the steps you advised me to do,  and in logcat SetFileHider says "Added file path: /storage/emulated/0/folder12onSD". Moreover, in the app, under the hidden files section, the folder name is good but the path exposed is /storage/emulated/0/folder12onSD. So the full path is not retained.

Here is my device info:
OS: LineageOS 18.1
Android version: 11
Amarok version: v0.8.1b2-foss

**Comment by deltazefiro** [comment]
OMG seems that I made a stupid mistake. I mistakenly took Android S as Android 11 :rofl:  
I've tested through Android 11 to 13 on virtual devices and I think it's working now. (For Android 10 or below there is another bug — about permission, I'm working on it.)
Try is:   [Amarok-v0.8.1b3-foss-cabb47e.apk](https://mega.nz/file/aXJHSCjY#VchKZ5MbNL-uDiUlwsDvhUq_knGrXDp8iHmOMVB1rOM)

**Comment by autodistries** [comment]
The debug version does work ! Thanks !

**Comment by marcossmtp** [comment]
> OMG seems that I made a stupid mistake. I mistakenly took Android S as Android 11 in the code 🤣 I've tested through Android 11 to 13 on virtual devices and I think it's working now. (For Android 10 or below there is another bug #17 — about permission, I'm working on it.) Try is: [Amarok-v0.8.1b3-foss-cabb47e.apk](https://mega.nz/file/aXJHSCjY#VchKZ5MbNL-uDiUlwsDvhUq_knGrXDp8iHmOMVB1rOM)

I tried that version in samsug s7 with oreo and it doesnt work.

**Comment by marcossmtp** [comment]
Not working

**Comment by deltazefiro** [comment]
@marcossmtp #17
